import { join, resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { chromium } from 'playwright';
import { CORPUS_ORIGIN, CORPUS_PAGES, CORPUS_ASSETS, pageHtml, assetBytes, sitemapXml } from './test/fixtures/corpus/index.mjs';
const ROOT = process.cwd();
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1600, height: 1000 } });
await ctx.route('**/*', async (route) => {
  const url = route.request().url(); const H = { 'access-control-allow-origin': '*' };
  if (url.startsWith('file://')) return route.continue();
  if (url.startsWith(CORPUS_ORIGIN)) {
    const path = url.slice(CORPUS_ORIGIN.length);
    const p = CORPUS_PAGES.find((x) => x.url === url || x.url.slice(CORPUS_ORIGIN.length) === path);
    if (p) return route.fulfill({ status: 200, contentType: 'text/html; charset=utf-8', body: pageHtml(p.id), headers: H });
    const a = CORPUS_ASSETS.find((x) => x.path === path);
    if (a) return route.fulfill({ status: 200, contentType: a.mime, body: Buffer.from(assetBytes(a.path)), headers: H });
    if (path === '/sitemap.xml') return route.fulfill({ status: 200, contentType: 'application/xml', body: sitemapXml(), headers: H });
    if (path === '/robots.txt') return route.fulfill({ status: 200, contentType: 'text/plain', body: `Sitemap: ${CORPUS_ORIGIN}/sitemap.xml\n`, headers: H });
    return route.fulfill({ status: 404, body: '', headers: H });
  }
  return route.abort();
});
const page = await ctx.newPage();
const errs = []; page.on('pageerror', e => errs.push(''+e));
await page.goto(pathToFileURL(join(ROOT, 'dist/pitchproof-studio.html')).href, { waitUntil: 'load' });
await page.waitForSelector('.st-app');
await page.keyboard.press('Alt+2'); await page.waitForTimeout(250);
await page.evaluate(() => { const i = [...document.querySelectorAll('input[type=text]')].find(x => (x.placeholder||'').includes('example.com')); i.focus(); i.select(); });
await page.keyboard.type(CORPUS_ORIGIN + '/');
await page.evaluate(() => [...document.querySelectorAll('button')].find(b => b.textContent.trim()==='Extract')?.click());
await page.waitForTimeout(3000);
console.log('blockers:', await page.evaluate(() => [...document.querySelectorAll('.st-blocker-code')].map(e=>e.textContent).join(', ') || '(emit panel not open)'));
console.log('review buttons:', await page.evaluate(() => [...document.querySelectorAll('button')].map(b=>b.textContent.trim()).filter(t=>/checked/i.test(t))));
console.log('review section present:', await page.evaluate(() => /Waiting for your review/.test(document.body.innerText)));
console.log('pending list:', await page.evaluate(() => (document.body.innerText.match(/Waiting for your review[\s\S]{0,420}/)||[''])[0].replace(/\n+/g,' | ').slice(0,420)));
console.log('contrast section:', await page.evaluate(() => (document.body.innerText.match(/Contrast · \d+[\s\S]{0,220}/)||[''])[0].replace(/\n+/g,' | ').slice(0,260)));
console.log('status:', await page.evaluate(() => (document.body.innerText.match(/\d+ things? block the emit[^\n]*|Ready to emit/)||[''])[0]));
await page.evaluate(() => [...document.querySelectorAll('button')].find(b=>/I have checked/i.test(b.textContent))?.click());
await page.waitForTimeout(500);
console.log('after review:', await page.evaluate(() => (document.body.innerText.match(/\d+ things? block the emit[^\n]*|Ready to emit/)||[''])[0]));
// --- F14: capture a specimen, then RUN the seed recipes ---
await page.keyboard.press('Alt+3'); await page.waitForTimeout(300);
const productUrl = (CORPUS_PAGES.find(p=>/product/.test(p.id)) || CORPUS_PAGES[1] || CORPUS_PAGES[0]).url;
console.log('capturing', productUrl);
await page.fill('input[data-st-act="specimen.urlDraft"]', productUrl);
await page.waitForTimeout(200);
console.log('url draft:', await page.inputValue('input[data-st-act="specimen.urlDraft"]'));
await page.evaluate(() => document.querySelector('[data-st-act="specimen.capture"]')?.click());
await page.waitForTimeout(4000);
console.log('specimens:', await page.evaluate(() => [...document.querySelectorAll('[data-st-act="specimen.select"]')].length));
console.log('specimen notices:', await page.evaluate(() => [...document.querySelectorAll('.st-notice-body')].map(e=>e.textContent.slice(0,160))));
await page.keyboard.press('Alt+4'); await page.waitForTimeout(300);
await page.evaluate(() => document.querySelector('[data-st-act="recipe.loadSeed"]')?.click());
await page.waitForTimeout(600);
console.log('recipes listed:', await page.evaluate(() => [...document.querySelectorAll('[data-st-act="recipe.select"]')].length));
console.log('run buttons:', await page.evaluate(() => [...document.querySelectorAll('[data-st-act="recipe.run"]:not([disabled])')].length));
await page.evaluate(() => document.querySelector('[data-st-act="recipe.runAll"]:not([disabled])')?.click());
await page.waitForTimeout(1500);
console.log('renditions after Run every recipe:', await page.evaluate(() => [...document.querySelectorAll('[data-st-act="rendition.select"]')].length));
console.log('toast:', await page.evaluate(() => (document.body.innerText.match(/\d+ renditions? from[^\n]*/)||[''])[0]));
await page.screenshot({ path: '.tmp-recipes.png' });
await page.keyboard.press('Alt+8'); await page.waitForTimeout(400);
console.log('emit blockers:', await page.evaluate(() => [...document.querySelectorAll('.st-blocker-code')].map(e=>e.textContent).join(', ')));
console.log('errors:', errs.slice(0,3));
await page.screenshot({ path: '.tmp-brand.png' });
await browser.close();
