/**
 * The committed demo artifact is current.
 *
 * `dist/northwind-demo.pitchproof.html` was hand-placed (CRITIQUE-2 C13).
 * Everything else in `dist/` is regenerated by the build, so a file sitting
 * beside them reads as current output — and it was not: 405 kB against a
 * current artifact of 597 kB. It still worked, which is the problem; it would
 * have gone on working, wrongly, indefinitely.
 *
 * §5's determinism is what makes this checkable at all: the same corpus proof
 * through the same pipeline produces the same bytes, so "is the committed file
 * what the code would produce today" is a question with an exact answer.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

import { emitDemo, DEMO_PATH } from '../../scripts/emit-demo.mjs';

test('dist/northwind-demo.pitchproof.html matches a fresh emit', async () => {
  assert.ok(existsSync(DEMO_PATH),
    'the demo artifact is missing — run `node scripts/emit-demo.mjs`');
  const onDisk = readFileSync(DEMO_PATH, 'utf8');
  const { html } = await emitDemo();
  assert.equal(onDisk.length, html.length,
    `the committed demo is ${onDisk.length} bytes; a fresh emit is ${html.length}. `
    + 'Run `node scripts/emit-demo.mjs`.');
  assert.equal(onDisk, html, 'the committed demo differs from a fresh emit');
});

test('the demo carries no severity-1 finding and reaches no network', async () => {
  const { html, findings } = await emitDemo();
  assert.deepEqual(findings.filter((f) => f.severity === 1).map((f) => f.code), []);
  // A demo is the file most likely to be opened by someone who will not read a
  // report, so the two laws it must obviously satisfy are asserted directly.
  assert.ok(!/\ssrc\s*=\s*["']https?:/i.test(html), 'the demo fetches something');
  assert.ok(!/@import\s+url\(\s*["']?https?:/i.test(html));
  assert.ok(html.includes('pp-provenance'), 'the demo carries no provenance label at all');
});
