/**
 * §17.6 determinism, plus the byte/hash/PRNG primitives every other lane
 * depends on. Reference values only — nothing here asserts against our own
 * implementation.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import zlib from 'node:zlib';
import { createHash } from 'node:crypto';

import { Pcg32, SeedBook, fnv1a64, toU64 } from '../../src/core/prng.js';
import { sha256Hex, sha256Bytes, stableStringify, contentHash, shortHash, fnv1a32 } from '../../src/core/hash.js';
import { base64Encode, base64Decode, utf8Encode, utf8Decode, toHex, fromHex, parseDataUri, utf8Length, concatBytes } from '../../src/core/bytes.js';
import { deflateRaw } from '../../src/core/deflate.js';
import { inflateRaw } from '../../src/core/inflate.js';
import { contentId, IdMinter, elementId, isMintedId } from '../../src/core/ids.js';

test('PCG32 matches the canonical XSH-RR vectors', () => {
  // The reference stream for seed 42, stream 54 published with the PCG source.
  const g = new Pcg32(42n, 54n);
  const got = Array.from({ length: 6 }, () => g.nextU32().toString(16).padStart(8, '0'));
  assert.deepEqual(got, ['a15c02b7', '7b47f409', 'ba1d3330', '83d2f293', 'bfa4784b', 'cbed606e']);
});

test('PCG32 reset replays exactly, and named substreams do not interfere', () => {
  const g = new Pcg32(42n, 54n);
  const a = [g.nextU32(), g.nextU32(), g.nextU32()];
  g.reset();
  assert.deepEqual([g.nextU32(), g.nextU32(), g.nextU32()], a);

  const book = new SeedBook('project-seed');
  const s1 = book.stream('kmeans');
  const s2 = book.stream('ids');
  const before = s1.nextU32();
  for (let i = 0; i < 100; i++) s2.nextU32();
  const fresh = book.fresh('kmeans');
  assert.equal(fresh.nextU32(), before, 'a substream must not depend on other substreams');
});

test('nextInt is unbiased at the boundary and never exceeds its bound', () => {
  const g = new Pcg32('bias-check');
  const counts = new Array(7).fill(0);
  for (let i = 0; i < 70000; i++) {
    const v = g.nextInt(7);
    assert.ok(v >= 0 && v < 7);
    counts[v] += 1;
  }
  // 70000 draws over 7 buckets: 10000 expected each. A modulo-biased generator
  // over a 2^32 range would skew by far less than this window, so the assertion
  // is about gross breakage, not about proving uniformity statistically.
  for (const c of counts) assert.ok(Math.abs(c - 10000) < 700, `bucket count ${c}`);
  assert.throws(() => g.nextInt(0));
  assert.throws(() => g.nextInt(-3));
});

test('toU64 and fnv1a64 are stable across calls', () => {
  assert.equal(fnv1a64(''), 0xcbf29ce484222325n);
  assert.equal(toU64('abc'), fnv1a64('abc'));
  assert.equal(toU64(-1), 0xffffffffffffffffn);
});

test('SHA-256 pads correctly at every block boundary', () => {
  // A message whose length is 55 mod 64 needs exactly one padding block. An
  // implementation that rounds up unconditionally allocates two and produces a
  // wrong digest for those lengths only, which no short test vector catches.
  for (const n of [0, 54, 55, 56, 63, 64, 65, 118, 119, 120, 311, 447, 448]) {
    const s = 'a'.repeat(n);
    assert.equal(sha256Hex(s), createHash('sha256').update(s).digest('hex'), `length ${n}`);
  }
});

test('SHA-256 matches the NIST vectors', () => {
  assert.equal(sha256Hex(''), 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855');
  assert.equal(sha256Hex('abc'), 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');
  assert.equal(
    sha256Hex('abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq'),
    '248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1',
  );
  assert.equal(sha256Hex('a'.repeat(1_000_000)), 'cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0');
});

test('SHA-256 agrees with node:crypto over generated byte payloads', () => {
  const g = new Pcg32('sha-cross');
  for (let i = 0; i < 80; i++) {
    const len = g.nextInt(400);
    const bytes = new Uint8Array(len);
    for (let k = 0; k < len; k++) bytes[k] = g.nextInt(256);
    const ours = toHex(sha256Bytes(bytes));
    const theirs = createHash('sha256').update(Buffer.from(bytes)).digest('hex');
    assert.equal(ours, theirs, `length ${len}`);
  }
});

test('stableStringify is key-order independent and rejects non-finite numbers', () => {
  assert.equal(stableStringify({ b: 1, a: 2 }), stableStringify({ a: 2, b: 1 }));
  assert.equal(stableStringify({ a: [1, { z: 1, y: 2 }] }), '{"a":[1,{"y":2,"z":1}]}');
  assert.equal(stableStringify({ a: undefined, b: 1 }), '{"b":1}');
  assert.equal(stableStringify(-0), '0');
  assert.throws(() => stableStringify({ a: NaN }), /non-finite/);
  const cyc = { a: 1 };
  cyc.self = cyc;
  assert.throws(() => stableStringify(cyc), /circular/);
});

test('content hashes and ids are content-derived and stable', () => {
  const a = { x: 1, y: [1, 2, 3] };
  const b = { y: [1, 2, 3], x: 1 };
  assert.equal(contentHash(a), contentHash(b));
  assert.equal(contentId('scene', a), contentId('scene', b));
  assert.notEqual(contentId('scene', a), contentId('beat', a));
  assert.match(contentId('scene', a), /^sc_[0-9a-f]{12}$/);
  assert.ok(isMintedId(contentId('scene', a)));
  assert.ok(isMintedId(elementId('sc_1', 'before/0')));
  assert.equal(shortHash(a, 8).length, 8);
  // Published FNV-1a 32 reference vectors.
  assert.equal(fnv1a32(''), 0x811c9dc5);
  assert.equal(fnv1a32('a'), 0xe40c292c);
  assert.equal(fnv1a32('foobar'), 0xbf9cf968);
});

test('IdMinter is reproducible and per-kind independent', () => {
  const m1 = new IdMinter('seed-1');
  const m2 = new IdMinter('seed-1');
  const a = [m1.next('scene'), m1.next('scene'), m1.next('beat')];
  const b = [m2.next('scene'), m2.next('scene'), m2.next('beat')];
  assert.deepEqual(a, b);

  const m3 = new IdMinter('seed-1');
  for (let i = 0; i < 50; i++) m3.next('beat');
  assert.equal(m3.next('scene'), new IdMinter('seed-1').next('scene'), 'kinds must not share a stream');

  assert.notEqual(new IdMinter('seed-2').next('scene'), a[0]);
  for (const id of a) assert.ok(isMintedId(id), id);
});

test('different seeds change ids without changing content hashes (§17.6)', () => {
  const scene = { layout: 'stack', headline: 'The same scene' };
  assert.equal(contentId('scene', scene), contentId('scene', scene));
  assert.notEqual(new IdMinter('seed-A').next('scene'), new IdMinter('seed-B').next('scene'));
});

test('base64, hex and UTF-8 round-trip', () => {
  const cases = ['', 'f', 'fo', 'foo', 'foob', 'fooba', 'foobar'];
  const expect = ['', 'Zg==', 'Zm8=', 'Zm9v', 'Zm9vYg==', 'Zm9vYmE=', 'Zm9vYmFy'];
  cases.forEach((s, i) => {
    assert.equal(base64Encode(utf8Encode(s)), expect[i], s);
    assert.equal(utf8Decode(base64Decode(expect[i])), s);
  });
  const bytes = new Uint8Array([0, 1, 254, 255, 128]);
  assert.equal(toHex(bytes), '0001feff80');
  assert.deepEqual([...fromHex('0001feff80')], [...bytes]);
  const unicode = 'héllo — 世界';
  assert.equal(utf8Length(unicode), utf8Encode(unicode).length);
  assert.equal(utf8Decode(utf8Encode(unicode)), unicode);
  assert.deepEqual([...concatBytes(new Uint8Array([1]), new Uint8Array([2, 3]))], [1, 2, 3]);
  assert.throws(() => base64Decode('!!!!'), /invalid character/);
});

test('parseDataUri reports what the emitter needs and rejects network URLs', () => {
  const d = parseDataUri('data:image/png;base64,iVBORw0KGgo=');
  assert.equal(d.mime, 'image/png');
  assert.equal(d.base64, true);
  assert.equal(d.bytes, 8);
  assert.equal(parseDataUri('https://example.com/x.png'), null);
  assert.equal(parseDataUri('//cdn.example.com/x.png'), null);
  assert.equal(parseDataUri('data:text/plain,hello').mime, 'text/plain');
});

test('DEFLATE round-trips against zlib in both directions', () => {
  const corpora = [
    '',
    'a',
    'abcabcabcabcabcabcabcabc',
    JSON.stringify({ scenes: Array.from({ length: 40 }, (_, i) => ({ id: `sc_${i}`, layout: 'splitBeforeAfter', beats: [1, 2, 3] })) }),
    base64Encode(utf8Encode('x'.repeat(4000))),
    Array.from({ length: 2000 }, (_, i) => String.fromCharCode(32 + (i * 7) % 95)).join(''),
  ];
  for (const text of corpora) {
    const input = utf8Encode(text);
    const ours = deflateRaw(input);
    assert.deepEqual([...zlib.inflateRawSync(Buffer.from(ours))], [...input], 'zlib must inflate our output');
    assert.deepEqual([...inflateRaw(ours, input.length)], [...input], 'we must inflate our own output');
    for (const level of [0, 1, 6, 9]) {
      const theirs = zlib.deflateRawSync(Buffer.from(input), { level });
      assert.deepEqual([...inflateRaw(new Uint8Array(theirs), input.length)], [...input], `level ${level}`);
    }
  }
});

test('DEFLATE is deterministic and competitive with zlib level 9 on model JSON', () => {
  const json = utf8Encode(JSON.stringify({
    spine: Array.from({ length: 30 }, (_, i) => ({
      id: `sc_${i.toString(16).padStart(12, '0')}`,
      layout: 'splitBeforeAfter',
      headline: `Scene ${i}: the same content, assembled from components`,
      beats: [{ id: `bt_${i}a`, reveals: [`el_${i}_0`, `el_${i}_1`], presenterNote: null, dwellHintMs: null }],
    })),
  }));
  const a = deflateRaw(json);
  const b = deflateRaw(json);
  assert.deepEqual([...a], [...b], 'two compressions of the same bytes must be identical');
  const z9 = zlib.deflateRawSync(Buffer.from(json), { level: 9 });
  // Our compressor beats zlib -9 on large model JSON and trails it slightly on
  // very small payloads, where zlib's static-tree heuristics win. Five percent
  // is the band that has to hold; the emitter keeps whichever of the compressed
  // and raw payloads is actually smaller either way (§13).
  assert.ok(a.length <= z9.length * 1.05 + 16, `ours ${a.length} vs zlib9 ${z9.length}`);
});

test('DEFLATE survives adversarial inputs', () => {
  const g = new Pcg32('deflate-fuzz');
  for (let i = 0; i < 40; i++) {
    const len = g.nextInt(9000);
    const bytes = new Uint8Array(len);
    const mode = i % 4;
    for (let k = 0; k < len; k++) {
      if (mode === 0) bytes[k] = g.nextInt(256);
      else if (mode === 1) bytes[k] = 65;
      else if (mode === 2) bytes[k] = 32 + (k % 3);
      else bytes[k] = g.nextInt(4) === 0 ? g.nextInt(256) : 97;
    }
    const out = deflateRaw(bytes);
    assert.deepEqual([...inflateRaw(out, len)], [...bytes], `mode ${mode} length ${len}`);
    assert.deepEqual([...zlib.inflateRawSync(Buffer.from(out))], [...bytes], `zlib mode ${mode} length ${len}`);
  }
});
