#!/usr/bin/env node
/**
 * The build (§5).
 *
 * Three outputs, all deterministic:
 *
 *   dist/pitchproof-runtime.js   the presentation runtime, bundled. Never
 *                                shipped alone — the studio embeds it as a
 *                                string and the emitter inlines it into every
 *                                artifact.
 *   dist/pitchproof-studio.html  the studio, single file, Netlify-deployable,
 *                                inline CSS and JS, no build server needed.
 *   dist/pitchproof-runtime.css  the artifact stylesheet, bundled, embedded the
 *                                same way as the runtime script.
 *
 * `--verify-repeat` builds everything twice and compares the bytes, which is
 * the §5 determinism law stated as a command. `--check` builds without writing.
 *
 * Zero npm dependencies (D3). Nothing here reads a clock or a random source, so
 * two runs on two machines from the same commit produce the same bytes.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from 'node:fs';
import { resolve, dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bundle, BundleError } from './lib/bundler.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
export const ROOT = resolve(HERE, '..');
export const SRC = join(ROOT, 'src');
export const DIST = join(ROOT, 'dist');

/** Modules bundled into the artifact runtime, and into the studio. */
const RUNTIME_ENTRY = join(SRC, 'runtime', 'index.js');
const STUDIO_ENTRY = join(SRC, 'ui', 'index.js');

const BANNER = [
  '/* PitchProof — generated by scripts/build.mjs. Do not edit. */',
  '/* This file contains no network references by construction; the emitter',
  '   re-verifies that on every artifact it writes (§13). */',
].join('\n');

/**
 * Every `.css` file in a directory tree, sorted by path so the concatenation is
 * deterministic regardless of how the filesystem enumerates.
 * @param {string} dir
 * @returns {string[]}
 */
export function cssFiles(dir) {
  if (!existsSync(dir)) return [];
  /** @type {string[]} */
  const out = [];
  const walk = (d) => {
    for (const name of readdirSync(d).sort()) {
      const p = join(d, name);
      if (statSync(p).isDirectory()) walk(p);
      else if (name.endsWith('.css')) out.push(p);
    }
  };
  walk(dir);
  return out;
}

/**
 * Concatenate a set of CSS files with a comment naming each.
 * @param {string[]} files
 * @returns {string}
 */
export function concatCss(files) {
  return files.map((f) => `/* ${relative(ROOT, f).split('\\').join('/')} */\n${readFileSync(f, 'utf8').trim()}`).join('\n\n');
}

/**
 * Escape a string so it can sit inside a `<script>` block as a JS string
 * literal without terminating the element or the literal.
 * @param {string} s
 * @returns {string}
 */
export function jsStringLiteral(s) {
  return JSON.stringify(s)
    .replace(/<\//g, '<\\/')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

/**
 * Build the artifact runtime bundle.
 * @returns {{js: string, css: string} | null} null when the runtime lane has not landed yet
 */
export function buildRuntime() {
  if (!existsSync(RUNTIME_ENTRY)) return null;
  const { code } = bundle({
    entry: RUNTIME_ENTRY,
    root: SRC,
    global: 'PitchProofRuntime',
    banner: BANNER,
  });
  // Every stylesheet that ships inside an artifact, in a fixed order: the
  // runtime's own chrome first, then the branch overlays, then the layouts, so
  // a layout rule can override a chrome default and never the other way round.
  const css = concatCss([
    ...cssFiles(join(SRC, 'runtime')),
    ...cssFiles(join(SRC, 'branch')),
    ...cssFiles(join(SRC, 'scene')),
  ]);
  return { js: code, css };
}

/**
 * Build the studio, with the runtime embedded as source strings so the emitter
 * can inline them into an artifact at runtime.
 * @param {{js: string, css: string} | null} runtime
 * @returns {string | null}
 */
export function buildStudio(runtime) {
  if (!existsSync(STUDIO_ENTRY)) return null;
  const { code } = bundle({ entry: STUDIO_ENTRY, root: SRC, global: 'PitchProofStudio', banner: BANNER });
  const css = concatCss(cssFiles(join(SRC, 'ui')));
  const shellPath = join(SRC, 'ui', 'shell.html');
  const shell = existsSync(shellPath) ? readFileSync(shellPath, 'utf8') : DEFAULT_SHELL;

  const embedded = [
    '<script>',
    'window.__PITCHPROOF_RUNTIME_JS__ = ' + jsStringLiteral(runtime ? runtime.js : '') + ';',
    'window.__PITCHPROOF_RUNTIME_CSS__ = ' + jsStringLiteral(runtime ? runtime.css : '') + ';',
    '</script>',
  ].join('\n');

  return shell
    .replace('<!--PITCHPROOF_STYLES-->', `<style>\n${css}\n</style>`)
    .replace('<!--PITCHPROOF_RUNTIME-->', embedded)
    .replace('<!--PITCHPROOF_SCRIPT-->', `<script>\n${code}\n</script>`);
}

const DEFAULT_SHELL = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PitchProof Studio</title>
<!--PITCHPROOF_STYLES-->
</head>
<body>
<div id="pp-studio-root"></div>
<!--PITCHPROOF_RUNTIME-->
<!--PITCHPROOF_SCRIPT-->
</body>
</html>
`;

/**
 * Produce every output as an in-memory map of path → contents.
 * @returns {{outputs: Map<string, string>, pending: string[]}}
 */
export function buildAll() {
  /** @type {Map<string, string>} */
  const outputs = new Map();
  /** @type {string[]} */
  const pending = [];

  const runtime = buildRuntime();
  if (runtime) {
    outputs.set('pitchproof-runtime.js', runtime.js);
    outputs.set('pitchproof-runtime.css', runtime.css);
  } else {
    pending.push('dist/pitchproof-runtime.js (src/runtime/index.js not present yet)');
  }

  const studio = buildStudio(runtime);
  if (studio) outputs.set('pitchproof-studio.html', studio);
  else pending.push('dist/pitchproof-studio.html (src/ui/index.js not present yet)');

  return { outputs, pending };
}

/** @param {Map<string, string>} outputs */
function write(outputs) {
  mkdirSync(DIST, { recursive: true });
  for (const [name, contents] of [...outputs].sort((a, b) => a[0].localeCompare(b[0]))) {
    writeFileSync(join(DIST, name), contents);
  }
}

/**
 * @param {Map<string, string>} a
 * @param {Map<string, string>} b
 * @returns {string[]} differing output names
 */
function diffOutputs(a, b) {
  const names = new Set([...a.keys(), ...b.keys()]);
  return [...names].sort().filter((n) => a.get(n) !== b.get(n));
}

function main() {
  const args = new Set(process.argv.slice(2));
  const verifyRepeat = args.has('--verify-repeat');
  const check = args.has('--check');

  let first;
  try {
    first = buildAll();
  } catch (e) {
    if (e instanceof BundleError) { console.error(`build: ${e.message}`); process.exit(1); }
    throw e;
  }

  if (verifyRepeat) {
    const second = buildAll();
    const differing = diffOutputs(first.outputs, second.outputs);
    if (differing.length) {
      console.error(`build: NOT deterministic — differing outputs: ${differing.join(', ')}`);
      process.exit(1);
    }
    console.log(`build: deterministic — ${first.outputs.size} output(s) byte-identical across two builds`);
  }

  if (!check) write(first.outputs);

  for (const [name, contents] of [...first.outputs].sort((a, b) => a[0].localeCompare(b[0]))) {
    console.log(`  ${check ? 'checked' : 'wrote'} dist/${name}  ${contents.length.toLocaleString('en-US')} bytes`);
  }
  for (const p of first.pending) console.log(`  pending  ${p}`);
  if (first.outputs.size === 0) console.log('build: nothing to emit yet — no lane has landed an entry point.');
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) main();
