#!/usr/bin/env node
/**
 * The build (§5).
 *
 * Three outputs, all deterministic:
 *
 *   dist/pitchproof-runtime.js   the presentation runtime, bundled. Never
 *                                shipped alone — the studio embeds it as a
 *                                string and the emitter inlines it into every
 *                                artifact.
 *   dist/pitchproof-studio.html  the studio, single file, Netlify-deployable,
 *                                inline CSS and JS, no build server needed.
 *   dist/pitchproof-runtime.css  the artifact stylesheet, bundled, embedded the
 *                                same way as the runtime script.
 *
 * `--verify-repeat` builds everything twice and compares the bytes, which is
 * the §5 determinism law stated as a command. `--check` builds without writing.
 *
 * Zero npm dependencies (D3). Nothing here reads a clock or a random source, so
 * two runs on two machines from the same commit produce the same bytes.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from 'node:fs';
import { resolve, dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bundle, BundleError } from './lib/bundler.mjs';
import { utf8Length } from '../src/core/bytes.js';
import { stripComments, stripCssComments, collapseBlankLines } from './lib/strip-comments.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
export const ROOT = resolve(HERE, '..');
export const SRC = join(ROOT, 'src');
export const DIST = join(ROOT, 'dist');

/**
 * The artifact entry is the composition root (`src/artifact.js`), not the bare
 * runtime. The runtime is deliberately layout- and branch-agnostic; something
 * has to put the three together, and if the bundle is built from
 * `src/runtime/index.js` an emitted artifact paints its opening beat from the
 * emitter's static HTML and then falls back to "Layout not registered" on the
 * presenter's first keypress.
 */
const RUNTIME_ENTRY = join(SRC, 'artifact.js');
const STUDIO_ENTRY = join(SRC, 'ui', 'index.js');

const BANNER = [
  '/* PitchProof — generated by scripts/build.mjs. Do not edit. */',
  '/* This file contains no network references by construction; the emitter',
  '   re-verifies that on every artifact it writes (§13). */',
  '/* Source comments are stripped from the bundle (scripts/lib/strip-comments.mjs).',
  '   Nothing else is: no renaming, no reformatting, no minification, and every',
  '   module is still keyed by its source path, so the artifact stays auditable by',
  '   the person who receives it (§18.4). The full commentary lives in src/. */',
].join('\n');

/**
 * Strip comments from a bundle, then put the banner back.
 *
 * The §20 critic measured 158,804 bytes of source comments in a 431,608-byte
 * runtime bundle — 36.8% of the file — riding inside every artifact, while §13's
 * budgeter progressively downscaled the *client's* images, which were 3.8% of
 * it. A degradation report that says a seller's hero image was resampled to 15%
 * while the largest removable payload was never considered is not a budget, it
 * is a scapegoat. The comments come out first; the images are budgeted against
 * what is left.
 *
 * `assertSameSurface` below is what makes this safe to do at all.
 *
 * @param {string} code
 * @param {string} banner
 * @returns {string}
 */
function stripBundle(code, banner) {
  const body = collapseBlankLines(stripComments(code));
  return `${banner}\n${body.startsWith('\n') ? body.slice(1) : body}`;
}

/**
 * Evaluate both bundles and assert the stripper changed nothing that runs.
 *
 * A scanner that mis-reads one regex literal or one apostrophe inside a comment
 * deletes live code, and the failure is silent — the bundle still parses, it
 * just does less. D5 is the precedent: `dist/pitchproof-studio.html` did not
 * parse at all while 1608 tests were green, because nothing executed the built
 * file. So the build executes both.
 *
 * @param {string} raw
 * @param {string} stripped
 * @param {string} globalName
 * @param {string} label
 */
function assertSameSurface(raw, stripped, globalName, label) {
  const surface = (code) => {
    const value = new Function(`${code}\n; return globalThis[${JSON.stringify(globalName)}];`)();
    return Object.keys(value || {}).sort();
  };
  /** @type {string[]} */
  let before;
  /** @type {string[]} */
  let after;
  try {
    before = surface(raw);
  } catch (e) {
    throw new BundleError(`${label}: the bundle does not evaluate even before stripping: ${e.message}`);
  }
  try {
    after = surface(stripped);
  } catch (e) {
    throw new BundleError(`${label}: comment stripping broke the bundle: ${e.message}`);
  }
  const lost = before.filter((n) => !after.includes(n));
  const gained = after.filter((n) => !before.includes(n));
  if (lost.length || gained.length) {
    throw new BundleError(
      `${label}: comment stripping changed the export surface — lost [${lost.join(', ')}], gained [${gained.join(', ')}]`);
  }
}

/**
 * Every `.css` file in a directory tree, sorted by path so the concatenation is
 * deterministic regardless of how the filesystem enumerates.
 * @param {string} dir
 * @returns {string[]}
 */
export function cssFiles(dir) {
  if (!existsSync(dir)) return [];
  /** @type {string[]} */
  const out = [];
  const walk = (d) => {
    for (const name of readdirSync(d).sort()) {
      const p = join(d, name);
      if (statSync(p).isDirectory()) walk(p);
      else if (name.endsWith('.css')) out.push(p);
    }
  };
  walk(dir);
  return out;
}

/**
 * Concatenate a set of CSS files with a comment naming each.
 * @param {string[]} files
 * @returns {string}
 */
export function concatCss(files) {
  return files.map((f) => `/* ${relative(ROOT, f).split('\\').join('/')} */\n${readFileSync(f, 'utf8').trim()}`).join('\n\n');
}

/**
 * Escape a string so it can sit inside a `<script>` block as a JS string
 * literal without terminating the element or the literal.
 * @param {string} s
 * @returns {string}
 */
export function jsStringLiteral(s) {
  return JSON.stringify(s)
    .replace(/<\//g, '<\\/')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

/**
 * Build the artifact runtime bundle.
 * @param {{stripComments?: boolean}} [options] `stripComments: false` keeps the
 *   source commentary, which is how the tests obtain something to compare the
 *   stripped bundle against. The build itself always strips.
 * @returns {{js: string, css: string} | null} null when the runtime lane has not landed yet
 */
export function buildRuntime(options = {}) {
  if (!existsSync(RUNTIME_ENTRY)) return null;
  const strip = options.stripComments !== false;
  const { code: raw } = bundle({
    entry: RUNTIME_ENTRY,
    root: SRC,
    global: 'PitchProofRuntime',
    banner: BANNER,
  });
  let code = raw;
  if (strip) {
    code = stripBundle(raw, BANNER);
    assertSameSurface(raw, code, 'PitchProofRuntime', 'dist/pitchproof-runtime.js');
  }
  // Every stylesheet that ships inside an artifact, in a fixed order: the
  // runtime's own chrome first, then the branch overlays, then the layouts, so
  // a layout rule can override a chrome default and never the other way round.
  const rawCss = concatCss([
    ...cssFiles(join(SRC, 'runtime')),
    ...cssFiles(join(SRC, 'branch')),
    ...cssFiles(join(SRC, 'scene')),
  ]);
  const css = strip ? collapseBlankLines(stripCssComments(rawCss)) : rawCss;
  return { js: code, css };
}

/**
 * Build the studio, with the runtime embedded as source strings so the emitter
 * can inline them into an artifact at runtime.
 * @param {{js: string, css: string} | null} runtime
 * @param {{stripComments?: boolean}} [options]
 * @returns {string | null}
 */
export function buildStudio(runtime, options = {}) {
  if (!existsSync(STUDIO_ENTRY)) return null;
  const strip = options.stripComments !== false;
  const { code: raw } = bundle({ entry: STUDIO_ENTRY, root: SRC, global: 'PitchProofStudio', banner: BANNER });
  let code = raw;
  if (strip) {
    code = stripBundle(raw, BANNER);
    assertSameSurface(raw, code, 'PitchProofStudio', 'dist/pitchproof-studio.html');
  }
  const rawCss = concatCss(cssFiles(join(SRC, 'ui')));
  const css = strip ? collapseBlankLines(stripCssComments(rawCss)) : rawCss;
  const shellPath = join(SRC, 'ui', 'shell.html');
  const shell = existsSync(shellPath) ? readFileSync(shellPath, 'utf8') : DEFAULT_SHELL;

  const embedded = [
    '<script>',
    'window.__PITCHPROOF_RUNTIME_JS__ = ' + jsStringLiteral(runtime ? runtime.js : '') + ';',
    'window.__PITCHPROOF_RUNTIME_CSS__ = ' + jsStringLiteral(runtime ? runtime.css : '') + ';',
    '</script>',
  ].join('\n');

  // Every replacement is a **function**, not a string. `String.replace` with a
  // string replacement expands `$'`, `$&` and `` $` `` — and the bundled sources
  // legitimately contain them: character tables in `core/text-metrics.js` and
  // `emit/scan-parse.js` hold a literal `'$'`, and `runtime/host.js` holds
  // `'\\$&'` in `cssEscape`. Each `$'` spliced the entire remainder of the
  // document into the middle of a string literal, so the studio parsed with a
  // syntax error, `PitchProofStudio` was never defined, and the built file
  // showed its own "bundle did not load" fallback. Every test passed, because
  // none of them opened the built studio in a browser. `test/integration/
  // studio.test.mjs` does now.
  return shell
    .replace('<!--PITCHPROOF_STYLES-->', () => `<style>\n${css}\n</style>`)
    .replace('<!--PITCHPROOF_RUNTIME-->', () => embedded)
    .replace('<!--PITCHPROOF_SCRIPT-->', () => `<script>\n${code}\n</script>`);
}

const DEFAULT_SHELL = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PitchProof Studio</title>
<!--PITCHPROOF_STYLES-->
</head>
<body>
<div id="pp-studio-root"></div>
<!--PITCHPROOF_RUNTIME-->
<!--PITCHPROOF_SCRIPT-->
</body>
</html>
`;

/**
 * Produce every output as an in-memory map of path → contents.
 * @returns {{outputs: Map<string, string>, pending: string[]}}
 */
export function buildAll() {
  /** @type {Map<string, string>} */
  const outputs = new Map();
  /** @type {string[]} */
  const pending = [];

  const runtime = buildRuntime();
  if (runtime) {
    outputs.set('pitchproof-runtime.js', runtime.js);
    outputs.set('pitchproof-runtime.css', runtime.css);
  } else {
    pending.push('dist/pitchproof-runtime.js (src/runtime/index.js not present yet)');
  }

  const studio = buildStudio(runtime);
  if (studio) outputs.set('pitchproof-studio.html', studio);
  else pending.push('dist/pitchproof-studio.html (src/ui/index.js not present yet)');

  return { outputs, pending };
}

/** @param {Map<string, string>} outputs */
function write(outputs) {
  mkdirSync(DIST, { recursive: true });
  for (const [name, contents] of [...outputs].sort((a, b) => a[0].localeCompare(b[0]))) {
    writeFileSync(join(DIST, name), contents);
  }
}

/**
 * @param {Map<string, string>} a
 * @param {Map<string, string>} b
 * @returns {string[]} differing output names
 */
function diffOutputs(a, b) {
  const names = new Set([...a.keys(), ...b.keys()]);
  return [...names].sort().filter((n) => a.get(n) !== b.get(n));
}

function main() {
  const args = new Set(process.argv.slice(2));
  const verifyRepeat = args.has('--verify-repeat');
  const check = args.has('--check');

  let first;
  try {
    first = buildAll();
  } catch (e) {
    if (e instanceof BundleError) { console.error(`build: ${e.message}`); process.exit(1); }
    throw e;
  }

  if (verifyRepeat) {
    const second = buildAll();
    const differing = diffOutputs(first.outputs, second.outputs);
    if (differing.length) {
      console.error(`build: NOT deterministic — differing outputs: ${differing.join(', ')}`);
      process.exit(1);
    }
    console.log(`build: deterministic — ${first.outputs.size} output(s) byte-identical across two builds`);
  }

  if (!check) write(first.outputs);

  for (const [name, contents] of [...first.outputs].sort((a, b) => a[0].localeCompare(b[0]))) {
    // `String.length` counts UTF-16 code units, not bytes, and this line called
    // them bytes: the build log said 2,773,619 for a studio that was 2,777,782
    // on disk. `emit()` has always used `utf8Length`; the build log was the one
    // place a number was reported in the wrong unit, which matters because §13's
    // whole budgeting story is told in bytes and a seller reading this line was
    // being told a smaller file than they have.
    console.log(`  ${check ? 'checked' : 'wrote'} dist/${name}  ${utf8Length(contents).toLocaleString('en-US')} bytes`);
  }
  for (const p of first.pending) console.log(`  pending  ${p}`);
  if (first.outputs.size === 0) console.log('build: nothing to emit yet — no lane has landed an entry point.');
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) main();
