#!/usr/bin/env node
/**
 * Emit the demonstration artifact, `dist/northwind-demo.pitchproof.html`.
 *
 * This exists because that file was hand-placed (CRITIQUE-2 C13). Everything
 * else in `dist/` is regenerated by `scripts/build.mjs`, so a file sitting
 * beside them reads as current output — and it was not: 405 kB against a
 * current artifact of 597 kB, still working, quietly rotting. A committed
 * artifact nobody can rebuild is a screenshot pretending to be a binary.
 *
 * The demo is the fixture corpus driven through the whole pipeline, which is
 * why this lives in `scripts/` and not in `build.mjs`: the build must not
 * depend on `test/`, and the corpus is a test fixture. `--check` compares the
 * committed file against a fresh emit without writing, which is what
 * `test/core/demo-artifact.test.mjs` runs — so the file cannot go stale
 * without a test failing. §5's determinism is what makes that comparison
 * possible at all.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
export const DEMO_PATH = join(ROOT, 'dist', 'northwind-demo.pitchproof.html');

/**
 * Build the demo artifact in memory.
 * @returns {Promise<{html: string, bytes: number, findings: any[]}>}
 */
export async function emitDemo() {
  const { buildCorpusProof } = await import('../test/fixtures/corpus/proof.mjs');
  const { corpusClock } = await import('../test/fixtures/corpus/index.mjs');
  const { emit } = await import('../src/emit/index.js');
  const { registerAllLayouts } = await import('../src/scene/index.js');
  const { buildRuntime } = await import('./build.mjs');

  registerAllLayouts();
  const runtime = buildRuntime();
  if (!runtime) throw new Error('emit-demo: the artifact runtime did not build');

  const proof = await buildCorpusProof();
  const result = await emit(proof, proof.emitOptions, {
    runtimeJs: runtime.js,
    runtimeCss: runtime.css,
    clock: corpusClock(),
  });
  if (!result.ok) {
    throw new Error(`emit-demo: the emitter refused the corpus proof — ${result.error}`);
  }
  return { html: result.value.html, bytes: result.value.bytes, findings: result.value.findings };
}

async function main() {
  const check = process.argv.includes('--check');
  const { html, bytes, findings } = await emitDemo();
  const severities = findings.reduce((acc, f) => ({ ...acc, [f.severity]: (acc[f.severity] || 0) + 1 }), {});

  if (check) {
    if (!existsSync(DEMO_PATH)) {
      console.error('emit-demo: dist/northwind-demo.pitchproof.html is missing. Run `node scripts/emit-demo.mjs`.');
      process.exit(1);
    }
    const onDisk = readFileSync(DEMO_PATH, 'utf8');
    if (onDisk !== html) {
      console.error(
        `emit-demo: dist/northwind-demo.pitchproof.html is stale — ${onDisk.length} bytes on disk, `
        + `${html.length} freshly emitted. Run \`node scripts/emit-demo.mjs\`.`);
      process.exit(1);
    }
    console.log(`emit-demo: dist/northwind-demo.pitchproof.html is current — ${bytes.toLocaleString('en-US')} bytes`);
    return;
  }

  mkdirSync(dirname(DEMO_PATH), { recursive: true });
  writeFileSync(DEMO_PATH, html);
  console.log(`  wrote dist/northwind-demo.pitchproof.html  ${bytes.toLocaleString('en-US')} bytes`);
  console.log(`  findings by severity  ${JSON.stringify(severities)}`);
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  main().catch((e) => { console.error(`emit-demo: ${e.message}`); process.exit(1); });
}
